### ISSUE TITLE
Getting Error when building SampleApp Project

### ISSUE THREAD

**Issue by anilreddy128** [romanpolunin/Fedlet#6]
Getting below error when trying to build sampleapp in Visual studio 2019.

Error		Project '..\Fedlet\Fedlet.csproj' targets 'netstandard2.0'. It cannot be referenced by a project that targets '.NETFramework,Version=v4.0'.	SampleApp			

Could you please help me here.

**Comment by romanpolunin** [comment]
You can't reference netstandard2.0 assemblies from .NET 4.0; upgrade to later version of NET 4.x.
